# .github/workflows/deploy.yml

name: GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/deploy.yml'
      - 'chunleili.github.io/**'
  pull_request:

jobs:
  deploy:
    name: Deploy to my Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          cache: yarn

      - name: build website
        working-directory: chunleili.github.io
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Deploy to my Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
